# -*- coding: utf-8 -*-
"""Assignment 1 students.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XPG_VP_hACfF8kdkwwWQdiSKLvyIOt4y
"""

# ============================================================
# INDIVIDUAL ASSIGNMENT 1 — SEARCH
# MASTER / INSTRUCTOR VERSION
# ============================================================
#
# Required files in the current working directory:
#
#   cities.csv
#   connections.csv
#
# IMPORTANT:
# - No absolute paths.
# - No Google Drive paths.
# - No machine-specific paths.
# - City names use one canonical normalization.
# - Successors are always processed alphabetically.
#
# ============================================================

# ============================================================
# PROVIDED TO STUDENTS
# 1. IMPORTS
# ============================================================

from dataclasses import dataclass
from pathlib import Path
from collections import deque
import heapq
import itertools
import json
import math
import re
import unicodedata

import pandas as pd
from IPython.display import display


# ============================================================
# PROVIDED TO STUDENTS
# 2. GLOBAL CONSTANTS
# ============================================================

CITIES_FILE = Path("cities.csv")
CONNECTIONS_FILE = Path("connections.csv")

EXPECTED_NUMBER_OF_CITIES = 20
EXPECTED_NUMBER_OF_CONNECTIONS = 35

EARTH_RADIUS_KM = 6371.0

EPS = 1e-12

# ============================================================
# PROVIDED TO STUDENTS
# 3. CANONICAL CITY NORMALIZATION
# ============================================================

def normalize_city(city):
    """
    Convert city names to one canonical representation.

    Examples
    --------
    "Bucharest"     -> "bucharest"
    " Iași "        -> "iasi"
    "Iasi"          -> "iasi"
    "Timișoara"     -> "timisoara"

    "Cluj-Napoca"   -> "cluj_napoca"
    "Cluj_Napoca"   -> "cluj_napoca"
    "Cluj Napoca"   -> "cluj_napoca"
    "Cluj–Napoca"   -> "cluj_napoca"

    Do not modify this function.
    """

    city = str(city).strip().lower()

    # Remove accents / diacritics.
    city = unicodedata.normalize(
        "NFKD",
        city,
    )

    city = "".join(
        character
        for character in city
        if not unicodedata.combining(character)
    )

    # Convert spaces, underscores and different dash
    # characters into one canonical separator.
    city = re.sub(
        r"[\s_\-–—−]+",
        "_",
        city,
    )

    city = city.strip("_")

    return city

# ============================================================
# PROVIDED TO STUDENTS
# 4. CHECK FILES
# ============================================================

if not CITIES_FILE.exists():
    raise FileNotFoundError(
        "cities.csv was not found in the current working directory."
    )

if not CONNECTIONS_FILE.exists():
    raise FileNotFoundError(
        "connections.csv was not found in the current working directory."
    )

# ============================================================
# PROVIDED TO STUDENTS
# 5. LOAD DATA
# ============================================================

cities_df = pd.read_csv(
    CITIES_FILE
)

connections_df = pd.read_csv(
    CONNECTIONS_FILE
)

# ============================================================
# PROVIDED TO STUDENTS
# 6. VALIDATE REQUIRED COLUMNS
# ============================================================

required_city_columns = {
    "city",
    "latitude",
    "longitude",
}

required_connection_columns = {
    "city_from",
    "city_to",
    "distance_km",
    "time_min",
}

missing_city_columns = (
    required_city_columns
    - set(cities_df.columns)
)

missing_connection_columns = (
    required_connection_columns
    - set(connections_df.columns)
)

if missing_city_columns:
    raise ValueError(
        "cities.csv is missing required columns: "
        f"{sorted(missing_city_columns)}"
    )

if missing_connection_columns:
    raise ValueError(
        "connections.csv is missing required columns: "
        f"{sorted(missing_connection_columns)}"
    )

# ============================================================
# PROVIDED TO STUDENTS
# 7. NORMALIZE CITY NAMES
# ============================================================

cities_df["city"] = (
    cities_df["city"]
    .map(normalize_city)
)

connections_df["city_from"] = (
    connections_df["city_from"]
    .map(normalize_city)
)

connections_df["city_to"] = (
    connections_df["city_to"]
    .map(normalize_city)
)

# ============================================================
# PROVIDED TO STUDENTS
# 8. CONVERT NUMERIC COLUMNS
# ============================================================

cities_df["latitude"] = (
    cities_df["latitude"]
    .astype(float)
)

cities_df["longitude"] = (
    cities_df["longitude"]
    .astype(float)
)

connections_df["distance_km"] = (
    connections_df["distance_km"]
    .astype(float)
)

connections_df["time_min"] = (
    connections_df["time_min"]
    .astype(float)
)

# ============================================================
# PROVIDED TO STUDENTS
# 9. DATASET INTEGRITY CHECKS
# ============================================================

# ------------------------------------------------------------
# Missing values
# ------------------------------------------------------------

assert not cities_df[
    [
        "city",
        "latitude",
        "longitude",
    ]
].isna().any().any(), (
    "cities.csv contains missing values."
)

'''
assert not connections_df[
    [
        "city_from",
    coordinates = {
        row["city"]: (
            float(row["latitude"]),
            float(row["longitude"])
        )
        for _, row in cities_df.iterrows()
)

# ------------------------------------------------------------
# Positive costs
# ------------------------------------------------------------

    GOAL = normalize_city("Rome")

        # ========================================================
        # ADMISSIBILITY
        # ========================================================
    admissibility_rows = []

    for state in graph:
        test_problem = Node(
            graph,
            initial_state=state, goal_state=GOAL)

        true_result = ucs(
            test_problem,
            cost="distance_km"
        )

        h = h_distance(
            state,
            GOAL
        )

        h_star = (true_result["distance_km"])

        admissibility_rows.append({
            "City":
                pretty_name(state),

            "h(n)":
                h,

            "h*(n)":
                h_star,

            "Admissible":
                h <= h_star + 1e-9})

    admissibility = pd.DataFrame(admissibility_rows)

    display(admissibility.round(2))

    print("Admissible for every state:", admissibility["Admissible"].all())

        # ========================================================
        # CONSISTENCY
        # ========================================================
    consistency_violations = []

    for state in graph:

        for neighbour in graph[state]:

            edge_cost = graph[
                state
            ][neighbour][
                "distance_km"
            ]

            h_state = h_distance(
                state,
                GOAL
            )

            h_neighbour = h_distance(
                neighbour,
                GOAL
            )

            if (h_state>edge_cost+h_neighbour+1e-9):

                consistency_violations.append({
                    "State":
                        pretty_name(state),

                    "Neighbour":
                        pretty_name(neighbour),

                    "h(n)":
                        h_state,

                    "c(n,n')":
                        edge_cost,

                    "h(n')":
                        h_neighbour
                })


    if len(consistency_violations) == 0:
        print("No consistency violations found.")

    else:
        display(pd.DataFrame(consistency_violations).round(2))
        )
    ]
    .unique()
    .tolist()
)

'''
assert not connections_df[
    ["city_from", "city_to", "distance_km", "time_min"]
].isna().any().any(), "connections.csv contains missing values."

assert (connections_df["distance_km"] > 0).all(), (
    "All distances must be positive."
)
assert (connections_df["time_min"] > 0).all(), (
    "All travel times must be positive."
)

connection_pairs = connections_df.apply(
    lambda row: tuple(sorted((row["city_from"], row["city_to"]))),
    axis=1,
)
duplicate_connections = connection_pairs[
    connection_pairs.duplicated(keep=False)
].unique().tolist()

assert not duplicate_connections, (
    "Duplicate undirected connections found: "
    f"{duplicate_connections}"
)

# ------------------------------------------------------------
# Expected dataset size
# ------------------------------------------------------------

assert len(cities_df) == EXPECTED_NUMBER_OF_CITIES, (
    "Unexpected number of cities. "
    f"Expected {EXPECTED_NUMBER_OF_CITIES}, "
    f"found {len(cities_df)}."
)

assert len(connections_df) == EXPECTED_NUMBER_OF_CONNECTIONS, (
    "Unexpected number of connections. "
    f"Expected {EXPECTED_NUMBER_OF_CONNECTIONS}, "
    f"found {len(connections_df)}."
)

# ============================================================
# PROVIDED TO STUDENTS
# 10. BUILD BIDIRECTIONAL GRAPH
# ============================================================

graph = {
    city: {}
    for city in cities_df["city"]
}

for row in connections_df.itertuples(
    index=False
):

    city_a = row.city_from
    city_b = row.city_to

    edge_data = {
        "distance_km":
            float(row.distance_km),

        "time_min":
            float(row.time_min),
    }

    graph[city_a][city_b] = (
        edge_data.copy()
    )

    graph[city_b][city_a] = (
        edge_data.copy()
    )

# ============================================================
# PROVIDED TO STUDENTS
# 11. CITY COORDINATES
# ============================================================

positions = {
    row.city: (
        float(row.latitude),
        float(row.longitude),
    )
    for row in cities_df.itertuples(
        index=False
    )
}

# ============================================================
# PROVIDED TO STUDENTS
# 12. GRAPH VALIDATION
# ============================================================

# ------------------------------------------------------------
# Check bidirectionality
# ------------------------------------------------------------

for city, neighbours in graph.items():

    for neighbour in neighbours:

        assert city in graph[neighbour], (
            "Graph is not bidirectional: "
            f"{city} -> {neighbour}"
        )

        assert math.isclose(
            graph[city][neighbour]["distance_km"],
            graph[neighbour][city]["distance_km"],
        )

        assert math.isclose(
            graph[city][neighbour]["time_min"],
            graph[neighbour][city]["time_min"],
        )

# ------------------------------------------------------------
# Check graph connectivity
# ------------------------------------------------------------

first_city = next(
    iter(graph)
)

visited = {
    first_city
}

stack = [
    first_city
]

while stack:

    current = stack.pop()

    for neighbour in graph[current]:

        if neighbour not in visited:

            visited.add(
                neighbour
            )

            stack.append(
                neighbour
            )


assert len(visited) == len(graph), (
    "The graph is not connected."
)

print(
    "Number of cities:",
    len(graph)
)

print(
    "Number of connections:",
    len(connections_df)
)

print(
    "Dataset loaded successfully."
)

print(
    "\nCanonical city identifiers:"
)

for city in sorted(graph):

    print(
        f"  - {city}"
    )

# ============================================================
# PROVIDED TO STUDENTS
# 13. SEARCH NODE
# ============================================================

@dataclass
class Node:

    state: str

    parent: "Node | None" = None

    path_cost: float = 0.0

    depth: int = 0

# ============================================================
# PROVIDED TO STUDENTS
# 14. SUCCESSORS
# ============================================================

def successors(state):
    """
    Return successor states in alphabetical order.

    Do not modify this function.
    """

    state = normalize_city(
        state
    )

    if state not in graph:
        raise KeyError(
            f"Unknown city: {state}"
        )

    return sorted(
        graph[state].keys()
    )

# ============================================================
# PROVIDED TO STUDENTS
# 15. RECONSTRUCT PATH
# ============================================================

def reconstruct_path(node):

    path = []

    while node is not None:

        path.append(
            node.state
        )

        node = (
            node.parent
        )

    return list(
        reversed(path)
    )

# ============================================================
# PROVIDED TO STUDENTS
# 16. PATH METRICS
# ============================================================

def path_metrics(path):

    if path is None:
        return {
            "path_length": None,
            "distance_km": None,
            "time_min": None,
        }

    distance = 0.0
    time = 0.0

    for city_a, city_b in zip(
        path[:-1],
        path[1:],
    ):

        distance += (
            graph[city_a]
            [city_b]
            ["distance_km"]
        )

        time += (
            graph[city_a]
            [city_b]
            ["time_min"]
        )

    return {
        "path_length":
            len(path) - 1,

        "distance_km":
            float(distance),

        "time_min":
            float(time),
    }

# ============================================================
# PROVIDED TO STUDENTS
# 17. VALIDATE PATH
# ============================================================

def validate_path(
    path,
    start,
    goal,
):

    if not path:
        return False

    start = normalize_city(
        start
    )

    goal = normalize_city(
        goal
    )

    # Require canonical city identifiers.
    if path[0] != start:
        return False

    if path[-1] != goal:
        return False

    for city in path:

        if city not in graph:
            return False

    for city_a, city_b in zip(
        path[:-1],
        path[1:],
    ):

        if city_b not in graph[city_a]:
            return False

    return True

# ============================================================
# PROVIDED TO STUDENTS
# 18. STANDARD RESULT FORMAT
# ============================================================

def build_result(
    algorithm,
    node,
    expanded_nodes,
    generated_nodes,
    max_frontier_size,
    expanded_order,
):

    # --------------------------------------------------------
    # Failure
    # --------------------------------------------------------

    if node is None:

        return {

            "algorithm":
                algorithm,

            "solution": {

                "found":
                    False,

                "path":
                    None,

                "path_length":
                    None,

                "distance_km":
                    None,

                "time_min":
                    None,
            },

            "diagnostics": {

                "expanded_nodes":
                    int(expanded_nodes),

                "generated_nodes":
                    int(generated_nodes),

                "max_frontier_size":
                    int(max_frontier_size),

                "expanded_order":
                    list(expanded_order),
            },
        }

    # --------------------------------------------------------
    # Success
    # --------------------------------------------------------

    path = reconstruct_path(
        node
    )

    metrics = path_metrics(
        path
    )

    return {

        "algorithm":
            algorithm,

        "solution": {

            "found":
                True,

            "path":
                path,

            **metrics,
        },

        "diagnostics": {

            "expanded_nodes":
                int(expanded_nodes),

            "generated_nodes":
                int(generated_nodes),

            "max_frontier_size":
                int(max_frontier_size),

            "expanded_order":
                list(expanded_order),
        },
    }

# ============================================================
# PROVIDED TO STUDENTS
# METRIC DEFINITIONS
# ============================================================
#
# expanded_nodes:
#
#   Number of nodes removed from the frontier for which
#   successors are generated.
#
#   A goal node is not counted as expanded if the search
#   stops immediately after selecting it.
#
#
# generated_nodes:
#
#   Number of child search nodes actually created and added
#   to the frontier.
#
#   The initial search node is not included.
#
#   A successor that is examined but discarded because its
#   state has already been reached (BFS/DFS), or because it
#   does not improve the best known path cost (UCS/A*), is
#   not counted as generated.
#
#
# max_frontier_size:
#
#   Maximum number of search nodes simultaneously stored
#   in the frontier.
#
#
# path_length:
#
#   Number of actions / graph edges in the returned path.
#
# ============================================================

import numpy as np
from itertools import count
'''
Already imported files.
cities_df = pd.read_csv(CITIES_FILE)

connections_df = pd.read_csv(CONNECTIONS_FILE)

I have just put in the following stuff for myself.
'''
def build_graph(connections_df):

    graph = {}

    for _, row in connections_df.iterrows():

        city_a = row["city_from"]
        city_b = row["city_to"]

        costs = {
            "distance_km": int(row["distance_km"]),
            "time_min": int(row["time_min"])
        }

        # Bidirectional connection
        graph.setdefault(city_a, {})[city_b] = costs
        graph.setdefault(city_b, {})[city_a] = costs

    return graph


graph = build_graph(connections_df)

def pretty_name(city):
    return city.replace("_", " ").replace("-", " ").title()

def expand(problem, node, cost="distance_km"):
    children = []

    for action in sorted(problem.actions(node.state)):

        next_state = problem.result(
            node.state,
            action
        )

        step_cost = problem.graph[
            node.state
        ][next_state][cost]

        child = Node(
            state=next_state,
            parent=node,
            action=action,
            path_cost=node.path_cost + step_cost,
            depth=node.depth + 1
        )

        children.append(child)

    return children
# ============================================================
# NOT PROVIDED
# TASK 1 — BREADTH-FIRST SEARCH
# ============================================================
def bfs(problem, trace=False):
    """
    Selection rule: shallowest node first
    Frontier: FIFO queue
    Repeated states: ignored once reached
    Goal test: when a child is generated
    """

    root = Node(
        state=problem.initial_state
    )

    if problem.is_goal(root.state):
        return build_result(
            problem,
            root,
            expanded_nodes=0,
            max_frontier=1
        )

    frontier = deque([root])

    reached = {
        root.state
    }

    expanded_nodes = 0
    max_frontier = 1
    step = 0

    while frontier:

        node = frontier.popleft()

        expanded_nodes += 1
        step += 1

        if trace:

            print(
                f"\nSTEP {step}"
            )

            print(
                "POP:",
                pretty_name(node.state)
            )

        for child in expand(
            problem,
            node,
            cost="distance_km"
        ):

            if child.state in reached:
                continue

            reached.add(child.state)

            # BFS can use an early goal test.
            if problem.is_goal(child.state):

                if trace:
                    print(
                        "GOAL GENERATED:",
                        pretty_name(child.state)
                    )

                max_frontier = max(
                    max_frontier,
                    len(frontier) + 1
                )

                return build_result(
                    problem,
                    child,
                    expanded_nodes,
                    max_frontier
                )

            frontier.append(child)

        max_frontier = max(
            max_frontier,
            len(frontier)
        )

        if trace:

            print(
                "Frontier:",
                [
                    pretty_name(n.state)
                    for n in frontier
                ]
            )

            print(
                "Reached:",
                [
                    pretty_name(s)
                    for s in sorted(reached)
                ]
            )

    return None

'''
run my stuff
source .venv/bin/activate
python3 assignment_1_students.py
'''

# ============================================================
# NOT PROVIDED
# TASK 2 — DEPTH-FIRST SEARCH
# ============================================================
def path_cost(problem, path, metric):
    """
    Compute a path's total distance or total time
    directly from the graph.
    """

    total = 0

    for city_a, city_b in zip(
        path[:-1],
        path[1:]
    ):
        total += problem.graph[
            city_a
        ][city_b][metric]

    return total

def make_result(
    problem,
    node,
    expanded_nodes,
    max_frontier
):
    """
    Create the same output structure for every algorithm.
    """

    path = successors(node)

    return {
        "path": path,
        "actions": len(path) - 1,
        "distance_km": path_cost(
            problem,
            path,
            "distance_km"
        ),
        "time_min": path_cost(
            problem,
            path,
            "time_min"
        ),
        "expanded_nodes": expanded_nodes,
        "max_frontier": max_frontier
    }
    
def dfs(problem, trace=False):

    root = Node(
        state=problem.initial_state
    )

    frontier = [root]

    reached = {
        root.state
    }

    expanded_nodes = 0
    max_frontier = 1
    step = 0

    while frontier:

        node = frontier.pop()

        step += 1

        if trace:

            print(
                f"\nSTEP {step}"
            )

            print(
                "POP:",
                pretty_name(node.state)
            )

        if problem.is_goal(node.state):

            return make_result(
                problem,
                node,
                expanded_nodes,
                max_frontier
            )

        expanded_nodes += 1

        children = []

        for child in expand(
            problem,
            node,
            cost="distance_km"
        ):

            if child.state not in reached:

                reached.add(child.state)

                children.append(child)

        # expand() returns alphabetical order.
        #
        # Example:
        #
        # [Belgrade, Budapest, Sofia]
        #
        # To visit Belgrade first with a LIFO stack,
        # push:
        #
        # Sofia, Budapest, Belgrade

        for child in reversed(children):
            frontier.append(child)

        max_frontier = max(
            max_frontier,
            len(frontier)
        )

        if trace:

            print(
                "Frontier:",
                [
                    pretty_name(n.state)
                    for n in reversed(frontier)
                ]
            )

            print(
                "Reached:",
                [
                    pretty_name(s)
                    for s in sorted(reached)
                ]
            )

    return None

# ============================================================
# NOT PROVIDED
# TASK 3 — UNIFORM-COST SEARCH
# ============================================================
def ucs(
    problem,
    cost="distance_km",
    trace=False
):
    """
    Uniform-Cost Search.

    Selection rule:
        lowest accumulated path cost g(n)

    Frontier:
        priority queue

    A state can be reached again if the new route
    is cheaper.

    Goal test:
        when the node is popped from the frontier
    """

    if cost not in {
        "distance_km",
        "time_min"
    }:
        raise ValueError(
            "cost must be 'distance_km' or 'time_min'"
        )

    root = Node(
        state=problem.initial_state,
        path_cost=0
    )

    tie_breaker = count()

    frontier = []

    heapq.heappush(
        frontier,
        (
            0,
            next(tie_breaker),
            root
        )
    )

    # reached[state] contains the cheapest
    # path cost discovered so far.
    reached = {
        root.state: 0
    }

    expanded_nodes = 0
    max_frontier = 1
    step = 0

    while frontier:

        current_cost, _, node = heapq.heappop(
            frontier
        )

        # There may be an older, more expensive entry
        # for the same state still inside the heap.
        #
        # If so, ignore it.
        if current_cost != reached.get(node.state):
            continue

        step += 1

        if trace:

            print(
                f"\nSTEP {step}"
            )

            print(
                f"POP: {pretty_name(node.state)} "
                f"g={current_cost}"
            )

        # UCS uses a late goal test.
        #
        # A generated goal is not necessarily optimal.
        # A goal popped with minimum g(n) is optimal.
        if problem.is_goal(node.state):

            return make_result(
                problem,
                node,
                expanded_nodes,
                max_frontier
            )

        expanded_nodes += 1

        for child in expand(
            problem,
            node,
            cost=cost
        ):

            child_cost = child.path_cost

            # Keep the child if:
            #
            # 1. we have never reached this state, or
            # 2. this is a cheaper path to the state.

            if (
                child.state not in reached
                or
                child_cost < reached[child.state]
            ):

                reached[child.state] = child_cost

                heapq.heappush(
                    frontier,
                    (
                        child_cost,
                        next(tie_breaker),
                        child
                    )
                )

        max_frontier = max(
            max_frontier,
            len(frontier)
        )

        if trace:

            active_frontier = []

            for g, _, n in frontier:

                if reached.get(n.state) == g:

                    active_frontier.append(
                        (
                            g,
                            pretty_name(n.state)
                        )
                    )

            active_frontier.sort()

            print(
                "Frontier:",
                active_frontier
            )

            print(
                "Reached:",
                {
                    pretty_name(s): g
                    for s, g
                    in sorted(reached.items())
                }
            )

    return None

# ============================================================
# PROVIDED TO STUDENTS
# TASK 4 — GEOGRAPHIC HEURISTIC FORMULA
# ============================================================
#
# Haversine distance:
#
# a =
#   sin²(Δlat / 2)
#   +
#   cos(lat1) cos(lat2) sin²(Δlon / 2)
#
# c =
#   2 asin(sqrt(a))
#
# distance =
#   R × c
#
# R = 6371 km
#
# Angles must be converted from degrees to radians.
#
# ============================================================
import math

# ============================================================
# NOT PROVIDED
# TASK 4 — HAVERSINE IMPLEMENTATION
# ============================================================
coordinates = {
    row["city"]: (
        float(row["latitude"]),
        float(row["longitude"])
    )
    for _, row in cities_df.iterrows()
}
def haversine(lat1, lon1, lat2, lon2):


    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)

    delta_phi = math.radians(lat2 - lat1)
    delta_lambda = math.radians(lon2 - lon1)

    a = (
        math.sin(delta_phi / 2) ** 2
        +
        math.cos(phi1)
        * math.cos(phi2)
        * math.sin(delta_lambda / 2) ** 2
    )

    c = 2 * math.atan2(
        math.sqrt(a),
        math.sqrt(1 - a)
    )

    return EARTH_RADIUS_KM * c

# ============================================================
# NOT PROVIDED
# TASK 4 — DISTANCE HEURISTIC
# ============================================================
def h_distance(state, goal="rome"):

    lat1, lon1 = coordinates[state]
    lat2, lon2 = coordinates[goal]

    return haversine(
        lat1,
        lon1,
        lat2,
        lon2
    )

print("h(Bucharest) =", round(h_distance("bucharest", "rome"), 2), "km")

print("h(Rome) =", round(h_distance("rome", "rome"), 2), "km")

# ============================================================
# PROVIDED TO STUDENTS
# TASK 5 — TIME HEURISTIC IDEA
# ============================================================
#
# Straight-line distance is measured in kilometres.
#
# A lower bound on travel time can be obtained by:
#
#     straight-line distance
#     ----------------------
#     maximum network speed
#
# ============================================================


# ============================================================
# NOT PROVIDED
# TASK 5 — TIME HEURISTIC IMPLEMENTATION
# ============================================================
def heuristic(state, goal="rome"):

    max_speed = connections_df["distance_km"].max() / connections_df["time_min"].min()

    return h_distance(state, goal) / max_speed


# ============================================================
# NOT PROVIDED
# TASK 6 — A*
# ============================================================
def astar(problem, heuristic, cost="distance_km", trace=False):

    root = Node(state=problem.initial_state, path_cost=0)

    tie_breaker = count()

    frontier = []

    root_h = heuristic(root.state)

    heapq.heappush(frontier,(root.path_cost + root_h, next(tie_breaker), root))

    # reached[state] = cheapest g(n) discovered so far
    reached = {root.state: 0}

    expanded_nodes = 0
    max_frontier = 1
    step = 0

    while frontier:
        f_value, _, node = heapq.heappop(frontier)

        # Ignore obsolete, more expensive paths.
        if (node.path_cost!=reached.get(node.state)):
            continue

        step += 1

        h_value = heuristic(node.state)

        if trace:
            print(f"\nSTEP {step}")

            print(
                f"POP: {pretty_name(node.state)} "
                f"g={node.path_cost:.2f} "
                f"h={h_value:.2f} "
                f"f={f_value:.2f}"
            )

        if problem.is_goal(node.state):

            return make_result(
                problem,
                node,
                expanded_nodes,
                max_frontier
            )

        expanded_nodes += 1

        for child in expand(
            problem,
            node,
            cost=cost
        ):

            child_g = (
                child.path_cost
            )

            if (
                child.state not in reached
                or
                child_g
                <
                reached[child.state]
            ):

                reached[
                    child.state
                ] = child_g

                child_h = heuristic(
                    child.state
                )

                child_f = (
                    child_g
                    +
                    child_h
                )

                heapq.heappush(
                    frontier,
                    (
                        child_f,
                        next(tie_breaker),
                        child
                    )
                )

        max_frontier = max(
            max_frontier,
            len(frontier)
        )

        if trace:

            active_frontier = []

            for f, _, n in frontier:

                if (
                    reached.get(n.state)
                    ==
                    n.path_cost
                ):

                    active_frontier.append(
                        (
                            round(f, 2),
                            pretty_name(n.state)
                        )
                    )

            active_frontier.sort()

            print(
                "Frontier:",
                active_frontier
            )

    return None


# ============================================================
# NOT PROVIDED
# INSTRUCTOR TOOL — TRUE OPTIMAL COSTS TO GOAL
# ============================================================
#
# Used to validate heuristics.
#
# This should NOT be part of the student implementation
# because it would reveal most of a UCS / Dijkstra solution.
# ============================================================


# ============================================================
# NOT PROVIDED
# INSTRUCTOR TOOL — HEURISTIC ANALYSIS
# ============================================================
'''
GOAL = normalize_city("Rome")

    # ========================================================
    # ADMISSIBILITY
    # ========================================================
admissibility_rows = []

for state in graph:
    test_problem = Node(
        graph,
        initial_state=state, goal_state=GOAL)

    true_result = ucs(
        test_problem,
        cost="distance_km"
    )

    h = h_distance(
        state,
        GOAL
    )

    h_star = (true_result["distance_km"])

    admissibility_rows.append({
        "City":
            pretty_name(state),

        "h(n)":
            h,

        "h*(n)":
            h_star,

        "Admissible":
            h <= h_star + 1e-9})

admissibility = pd.DataFrame(admissibility_rows)

display(admissibility.round(2))

print("Admissible for every state:", admissibility["Admissible"].all())

    # ========================================================
    # CONSISTENCY
    # ========================================================
consistency_violations = []

for state in graph:

    for neighbour in graph[state]:

        edge_cost = graph[
            state
        ][neighbour][
            "distance_km"
        ]

        h_state = h_distance(
            state,
            GOAL
        )

        h_neighbour = h_distance(
            neighbour,
            GOAL
        )

        if (h_state>edge_cost+h_neighbour+1e-9):

            consistency_violations.append({
                "State":
                    pretty_name(state),

                "Neighbour":
                    pretty_name(neighbour),

                "h(n)":
                    h_state,

                "c(n,n')":
                    edge_cost,

                "h(n')":
                    h_neighbour
            })


if len(consistency_violations) == 0:
    print("No consistency violations found.")

else:
    display(pd.DataFrame(consistency_violations).round(2))

# ============================================================
# PROVIDED TO STUDENTS
# 19. MAIN SEARCH PROBLEM
# ============================================================

'''
START = normalize_city(
    "Bucharest"
)

GOAL = normalize_city(
    "Rome"
)


assert START in graph, (
    f"Unknown initial state: {START}"
)

assert GOAL in graph, (
    f"Unknown goal state: {GOAL}"
)

assert START != GOAL, (
    "Initial state and goal state must be different."
)


print(
    "\nInitial state:",
    START
)

print(
    "Goal state:",
    GOAL
)


# ============================================================
# NOT PROVIDED
# 20. RUN REFERENCE SEARCH ALGORITHMS
# ============================================================
def run_reference_search(
    algorithm,
    start,
    goal,
    cost="distance_km",
    heuristic_fn=None,
):
    root = Node(state=start)
    is_depth_first = algorithm == "DFS"
    is_breadth_first = algorithm == "BFS"
    uses_costs = not (is_depth_first or is_breadth_first)
    tie_breaker = itertools.count()

    if is_breadth_first:
        frontier = deque([root])
    elif is_depth_first:
        frontier = [root]
    else:
        root_h = heuristic_fn(start) if heuristic_fn else 0.0
        frontier = [(root.path_cost + root_h, next(tie_breaker), root)]

    reached = {start: 0.0} if uses_costs else {start}
    expanded_nodes = 0
    generated_nodes = 0
    max_frontier_size = 1
    expanded_order = []

    while frontier:
        if is_breadth_first:
            node = frontier.popleft()
        elif is_depth_first:
            node = frontier.pop()
        else:
            priority, _, node = heapq.heappop(frontier)
            if node.path_cost != reached.get(node.state):
                continue

        if node.state == goal:
            return build_result(
                algorithm,
                node,
                expanded_nodes,
                generated_nodes,
                max_frontier_size,
                expanded_order,
            )

        expanded_nodes += 1
        expanded_order.append(node.state)
        neighbours = successors(node.state)
        if is_depth_first:
            neighbours = list(reversed(neighbours))

        for neighbour in neighbours:
            step_cost = graph[node.state][neighbour][cost]
            child_cost = node.path_cost + step_cost

            if uses_costs:
                if child_cost >= reached.get(neighbour, math.inf):
                    continue
                reached[neighbour] = child_cost
            else:
                if neighbour in reached:
                    continue
                reached.add(neighbour)

            child = Node(
                state=neighbour,
                parent=node,
                path_cost=child_cost,
                depth=node.depth + 1,
            )

            if is_breadth_first:
                frontier.append(child)
            elif is_depth_first:
                frontier.append(child)
            else:
                h_value = heuristic_fn(neighbour) if heuristic_fn else 0.0
                heapq.heappush(
                    frontier,
                    (
                        child_cost + h_value,
                        next(tie_breaker),
                        child,
                    ),
                )
            generated_nodes += 1

        max_frontier_size = max(max_frontier_size, len(frontier))

    return build_result(
        algorithm,
        None,
        expanded_nodes,
        generated_nodes,
        max_frontier_size,
        expanded_order,
    )


reference_results = {
    "BFS": run_reference_search("BFS", START, GOAL),
    "DFS": run_reference_search("DFS", START, GOAL),
    "UCS-distance": run_reference_search(
        "UCS-distance", START, GOAL, cost="distance_km"
    ),
    "UCS-time": run_reference_search(
        "UCS-time", START, GOAL, cost="time_min"
    ),
    "A*-distance": run_reference_search(
        "A*-distance",
        START,
        GOAL,
        cost="distance_km",
        heuristic_fn=lambda state: h_distance(state, GOAL),
    ),
    "A*-time": run_reference_search(
        "A*-time",
        START,
        GOAL,
        cost="time_min",
        heuristic_fn=lambda state: heuristic(state, GOAL),
    ),
}


# ============================================================
# NOT PROVIDED
# 21. VALIDATE ALL RETURNED PATHS
# ============================================================
for name, result in reference_results.items():

    solution = result["solution"]

    if solution["found"]:
        path = solution["path"]

        assert validate_path(
            path,
            START,
            GOAL,
        ), f"{name} returned an invalid path."

        recalculated_metrics = path_metrics(path)

        assert math.isclose(
            solution["distance_km"],
            recalculated_metrics["distance_km"],
            rel_tol=1e-9,
        ), f"{name} has an incorrect distance."

        assert math.isclose(
            solution["time_min"],
            recalculated_metrics["time_min"],
            rel_tol=1e-9,
        ), f"{name} has an incorrect travel time."

        print(f"{name}: valid path")

    else:
        print(f"{name}: no path found")


# ============================================================
# NOT PROVIDED
# 22. HEURISTIC ANALYSIS
# ============================================================
heuristic_rows = []

for state in sorted(graph):
    optimal_result = run_reference_search(
        "UCS-distance",
        state,
        GOAL,
        cost="distance_km",
    )

    true_cost = optimal_result["solution"]["distance_km"]
    heuristic_value = h_distance(state, GOAL)

    heuristic_rows.append({
        "city": pretty_name(state),
        "heuristic": heuristic_value,
        "true_cost": true_cost,
        "admissible": (
            heuristic_value <= true_cost + EPS
        ),
    })

heuristic_analysis = pd.DataFrame(
    heuristic_rows
)

display(
    heuristic_analysis.round(2)
)

print(
    "Admissible for every city:",
    heuristic_analysis["admissible"].all(),
)

consistency_violations = []

for city in sorted(graph):

    for neighbour in sorted(graph[city]):

        edge_cost = graph[city][neighbour]["distance_km"]

        left_side = h_distance(city, GOAL)

        right_side = (
            edge_cost
            + h_distance(neighbour, GOAL)
        )

        if left_side > right_side + EPS:
            consistency_violations.append({
                "city": pretty_name(city),
                "neighbour": pretty_name(neighbour),
                "h(city)": left_side,
                "edge_cost": edge_cost,
                "h(neighbour)": h_distance(
                    neighbour,
                    GOAL,
                ),
            })

if consistency_violations:
    print("Consistency violations found:")
    display(
        pd.DataFrame(
            consistency_violations
        ).round(2)
    )
else:
    print("The distance heuristic is consistent.")
    


# ============================================================
# PROVIDED TO STUDENTS
# 23. SUMMARY TABLE HELPER
# ============================================================

def make_summary_row(name, result):

    solution = (result["solution"])

    diagnostics = (result["diagnostics"])


    return {"algorithm": name,

        "path":
            (
                " -> ".join(
                    solution["path"]
                )

                if solution["path"]

                else None
            ),


        "actions":
            solution[
                "path_length"
            ],


        "distance_km":
            solution[
                "distance_km"
            ],


        "time_min":
            solution[
                "time_min"
            ],


        "expanded":
            diagnostics[
                "expanded_nodes"
            ],


        "generated":
            diagnostics[
                "generated_nodes"
            ],


        "max_frontier":
            diagnostics[
                "max_frontier_size"
            ],
    }


# ============================================================
# NOT PROVIDED
# 24. CREATE COMPARISON TABLE
# ============================================================
comparison_table = pd.DataFrame(
    [
        make_summary_row(name, result)
        for name, result in reference_results.items()
    ]
)

display(comparison_table.round(2))


# ============================================================
# NOT PROVIDED
# 25. PRINT PATHS AND EXPANSION ORDERS
# ============================================================
for name, result in reference_results.items():
    solution = result["solution"]
    diagnostics = result["diagnostics"]
    readable_path = (
        " -> ".join(pretty_name(city) for city in solution["path"])
        if solution["path"]
        else "No path found"
    )

    print(f"\n{name} path: {readable_path}")
    print(
        f"{name} expansion order: "
        f"{' -> '.join(pretty_name(city) for city in diagnostics['expanded_order'])}"
    )


# ============================================================
# NOT PROVIDED
# 26. PRINT HEURISTIC ANALYSIS
# ============================================================
print("\nDistance heuristic analysis:")
display(heuristic_analysis.round(2))
print(
    "Admissible for every city:",
    bool(heuristic_analysis["admissible"].all()),
)

if consistency_violations:
    print("Consistency violations:")
    display(pd.DataFrame(consistency_violations).round(2))
else:
    print("The distance heuristic is consistent.")


# ============================================================
# NOT PROVIDED
# 27. SANITY CHECKS
# ============================================================
for name, result in reference_results.items():
    solution = result["solution"]
    diagnostics = result["diagnostics"]

    assert solution["found"], f"{name} did not find a path."
    assert validate_path(solution["path"], START, GOAL), (
        f"{name} returned an invalid path."
    )
    assert solution["path_length"] == len(solution["path"]) - 1
    assert diagnostics["expanded_nodes"] == len(diagnostics["expanded_order"])
    assert diagnostics["generated_nodes"] >= 0
    assert diagnostics["max_frontier_size"] >= 1

    recalculated = path_metrics(solution["path"])
    for metric in ("distance_km", "time_min"):
        assert math.isclose(
            solution[metric],
            recalculated[metric],
            rel_tol=1e-9,
        ), f"{name} has an incorrect {metric}."

assert bool(heuristic_analysis["admissible"].all()), (
    "The distance heuristic must be admissible for every city."
)
assert not consistency_violations, (
    "The distance heuristic must be consistent."
)
print("All search and heuristic sanity checks passed.")


# ============================================================
# NOT PROVIDED
# 28. BUILD FINAL RESULTS OBJECT
# ============================================================
#
# Notice:
#
# Search results are divided into:
results = {
    **reference_results,
    "_metadata": {
        "start": START,
        "goal": GOAL,
        "heuristic_analysis": {
            "admissible_for_all_cities": bool(
                heuristic_analysis["admissible"].all()
            ),
            "consistent": not consistency_violations,
            "consistency_violations": consistency_violations,
            "cities": heuristic_rows,
        },
    },
}
#     solution
#     diagnostics
#
# The solution fields are the strongest candidates for
# strict automatic grading.
#
# Diagnostics are useful for debugging and understanding
# search behaviour.
#
# ============================================================




# ============================================================
# PROVIDED TO STUDENTS
# 29. EXPORT RESULTS.JSON
# ============================================================

OUTPUT_FILE = Path(
    "results.json"
)

#remove quotes once I get here
with open(
    OUTPUT_FILE,
    "w",
    encoding="utf-8",
) as f:

    json.dump(
        results,
        f,
        indent=2,
        ensure_ascii=False,
    )


print()

print(
    f"Created: {OUTPUT_FILE}"
)


# ============================================================
# PROVIDED TO STUDENTS
# 30. VERIFY EXPORTED JSON
# ============================================================

with open(
    OUTPUT_FILE,
    "r",
    encoding="utf-8",
) as f:

    loaded_results = (
        json.load(f)
    )


assert (loaded_results == results), ("results.json does not match the results " "generated by the notebook.")


print("results.json matches the results "
    "generated by the notebook.")

#submit this notebook and the jason it has generated with the solutions