# -*- coding: utf-8 -*-
"""Session - 04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P5OswD3qWYH2G6EdF2Ej2cRrk9cLwfaX
"""

# ============================================================
# SESSION 4 — FINAL EXERCISE: SOLUTION
# Uninformed Search — Bucharest → Rome
#
# This notebook is self-contained.
# Required files:
#   - cities.csv
#   - connections.csv
# ============================================================


# ============================================================
# 0. IMPORTS
# ============================================================

from dataclasses import dataclass
from collections import deque
from itertools import count
import heapq
import pandas as pd


# ============================================================
# 1. LOAD DATA
# ============================================================

cities = pd.read_csv("cities.csv")
connections = pd.read_csv("connections.csv")


# ============================================================
# 2. VALIDATE DATASET STRUCTURE
# ============================================================

required_city_columns = {
    "city",
    "latitude",
    "longitude"
}

required_connection_columns = {
    "city_from",
    "city_to",
    "distance_km",
    "time_min"
}

missing_city_columns = required_city_columns - set(cities.columns)
missing_connection_columns = (
    required_connection_columns - set(connections.columns)
)

if missing_city_columns:
    raise ValueError(
        f"Missing columns in cities.csv: "
        f"{sorted(missing_city_columns)}"
    )

if missing_connection_columns:
    raise ValueError(
        f"Missing columns in connections.csv: "
        f"{sorted(missing_connection_columns)}"
    )


# ============================================================
# 3. NORMALISE CITY IDs
# ============================================================

def normalize_city(city):
    """
    Convert city names to a consistent internal representation.

    Examples:
        "Bucharest"   -> "bucharest"
        "Cluj-Napoca" -> "cluj-napoca"
    """
    return str(city).strip().lower()


cities["city"] = cities["city"].apply(normalize_city)

connections["city_from"] = (
    connections["city_from"].apply(normalize_city)
)

connections["city_to"] = (
    connections["city_to"].apply(normalize_city)
)


# ============================================================
# 4. BUILD GRAPH
# ============================================================

def build_graph(connections_df):
    """
    Build an adjacency dictionary.

    graph["bucharest"]["belgrade"] =
        {
            "distance_km": ...,
            "time_min": ...
        }

    Every connection is added in both directions.
    """

    graph = {}

    for _, row in connections_df.iterrows():

        city_a = row["city_from"]
        city_b = row["city_to"]

        costs = {
            "distance_km": int(row["distance_km"]),
            "time_min": int(row["time_min"])
        }

        # Bidirectional connection
        graph.setdefault(city_a, {})[city_b] = costs
        graph.setdefault(city_b, {})[city_a] = costs

    return graph


graph = build_graph(connections)


# ============================================================
# 5. DEFINE SEARCH PROBLEM
# ============================================================

class RouteProblem:

    def __init__(
        self,
        graph,
        initial_state="bucharest",
        goal_state="rome"
    ):
        self.graph = graph
        self.initial_state = normalize_city(initial_state)
        self.goal_state = normalize_city(goal_state)

    def actions(self, state):
        """
        Return the cities directly reachable from state.
        """
        return list(self.graph[state].keys())

    def result(self, state, action):
        """
        In this route problem, the action itself tells us
        the destination city.
        """
        return action

    def is_goal(self, state):
        return state == self.goal_state

    def action_cost(self, state, action, next_state):
        """
        Default action cost used in previous examples:
        distance in kilometres.
        """
        return self.graph[state][next_state]["distance_km"]


problem = RouteProblem(
    graph,
    initial_state="bucharest",
    goal_state="rome"
)


# ============================================================
# 6. HELPER FUNCTIONS
# ============================================================

def pretty_name(city):
    """
    Convert internal city IDs into readable names.
    """
    return city.replace("_", " ").replace("-", " ").title()


def validate_problem(problem):
    """
    Check that start and goal exist in the graph.
    """

    if problem.initial_state not in problem.graph:
        raise ValueError(
            f"Initial state '{problem.initial_state}' "
            f"is not present in the graph."
        )

    if problem.goal_state not in problem.graph:
        raise ValueError(
            f"Goal state '{problem.goal_state}' "
            f"is not present in the graph."
        )


validate_problem(problem)


# ============================================================
# 7. DATASET INFORMATION
# ============================================================

print("Initial state:", problem.initial_state)
print("Goal state:", problem.goal_state)

print("Cities:", len(graph))

print(
    "Connections:",
    sum(
        len(neighbours)
        for neighbours in graph.values()
    ) // 2
)

print("\nCities in graph:")
print(sorted(graph.keys()))


# ============================================================
# 8. SEARCH NODE
# ============================================================

@dataclass
class Node:

    state: str
    parent: object = None
    action: object = None
    path_cost: float = 0
    depth: int = 0


# A search node represents one particular way
# of reaching a state.
#
# STATE     -> where we are
# PARENT    -> the search node we came from
# ACTION    -> the action used to get here
# PATH-COST -> accumulated cost g(n)
# DEPTH     -> number of actions from the root


# ============================================================
# 9. EXPAND
# ============================================================

def expand(problem, node, cost="distance_km"):
    """
    Generate the children of a search node.

    Successors are considered alphabetically so that
    all runs are deterministic.

    Child path cost:

        child.PATH-COST
        =
        parent.PATH-COST
        +
        ACTION-COST(s, action, s')
    """

    children = []

    for action in sorted(problem.actions(node.state)):

        next_state = problem.result(
            node.state,
            action
        )

        step_cost = problem.graph[
            node.state
        ][next_state][cost]

        child = Node(
            state=next_state,
            parent=node,
            action=action,
            path_cost=node.path_cost + step_cost,
            depth=node.depth + 1
        )

        children.append(child)

    return children


# ============================================================
# 10. SOLUTION HELPERS
# ============================================================

def solution_path(node):
    """
    Reconstruct the path from the initial state
    to the current node.
    """

    path = []

    while node is not None:
        path.append(node.state)
        node = node.parent

    return list(reversed(path))


def solution_actions(node):
    """
    Reconstruct the sequence of actions.
    """

    actions = []

    while node is not None and node.parent is not None:
        actions.append(node.action)
        node = node.parent

    return list(reversed(actions))


def path_cost(problem, path, metric):
    """
    Compute a path's total distance or total time
    directly from the graph.
    """

    total = 0

    for city_a, city_b in zip(
        path[:-1],
        path[1:]
    ):
        total += problem.graph[
            city_a
        ][city_b][metric]

    return total


def make_result(
    problem,
    node,
    expanded_nodes,
    max_frontier
):
    """
    Create the same output structure for every algorithm.
    """

    path = solution_path(node)

    return {
        "path": path,
        "actions": len(path) - 1,
        "distance_km": path_cost(
            problem,
            path,
            "distance_km"
        ),
        "time_min": path_cost(
            problem,
            path,
            "time_min"
        ),
        "expanded_nodes": expanded_nodes,
        "max_frontier": max_frontier
    }

# ============================================================
# 11. PART 1 — INITIAL SEARCH NODE
# ============================================================

initial_node = Node(
    state=problem.initial_state,
    parent=None,
    action=None,
    path_cost=0,
    depth=0
)

print("\nINITIAL SEARCH NODE")
print(initial_node)

# ============================================================
# 12. PART 1 — EXPAND BUCHAREST
# ============================================================

print("\nCHILDREN GENERATED FROM BUCHAREST")

initial_children = expand(
    problem,
    initial_node,
    cost="distance_km"
)

for child in initial_children:

    print(
        f"{pretty_name(child.state):15s}"
        f" depth={child.depth}"
        f" path_cost={child.path_cost} km"
    )


# Expansion only generates alternatives.
#
# It does NOT determine which child will be explored next.
#
# The search strategy determines that:
#
# BFS -> shallowest node
# DFS -> deepest node
# UCS -> lowest path cost g(n)


# ============================================================
# EXERCISE — EXPAND BUCHAREST
# ============================================================
# Assuming successors are considered in alphabetical order:
#
# Bucharest -> Belgrade
#           -> Budapest
#           -> Sofia
#
# 1. Child search nodes generated:
#
#     Belgrade-node
#     Budapest-node
#     Sofia-node
#
# 2. Frontier after expanding Bucharest:
#
#     Frontier = [
#         Belgrade-node,
#         Budapest-node,
#         Sofia-node
#     ]
#
# At this exact moment, the frontier contains exactly
# the newly generated search nodes.
#
# 3. States reached so far:
#
#     Reached = {
#         Bucharest,
#         Belgrade,
#         Budapest,
#         Sofia
#     }
#
# Key distinction:
#
# Generated now:
#     Belgrade-node, Budapest-node, Sofia-node
#
# Frontier:
#     search nodes waiting to be explored
#
# Reached:
#     states discovered at any point so far
#
# Important:
#     Frontier contains SEARCH NODES.
#     Reached contains STATES.



# ============================================================
# EXERCISE — WHICH NODE IS EXPANDED NEXT?
# ============================================================
# What determines which node is expanded next?
#
# BFS:
#     Expands the SHALLOWEST node in the frontier.
#     It uses a FIFO queue.
#
# DFS:
#     Expands the DEEPEST node in the frontier.
#     It uses a LIFO stack.
#
# UCS:
#     Expands the node with the LOWEST accumulated
#     path cost g(n).
#     It uses a priority queue.
#
#
# In short:
#
#     BFS -> minimum depth
#     DFS -> maximum depth
#     UCS -> minimum g(n)
#
#
# IMPORTANT:
# None of these algorithms estimates which node is
# geographically closer to Rome.
# That would require heuristic information.
# ============================================================
# AFTER THE FIRST EXPANSION
# ============================================================
# After expanding Bucharest:
#
# Generated:
#     Belgrade-node
#     Budapest-node
#     Sofia-node
#
# Frontier:
#     [Belgrade-node, Budapest-node, Sofia-node]
#
# Reached:
#     {Bucharest, Belgrade, Budapest, Sofia}
# ============================================================
# EXPAND THE NEXT NODE — BFS / DFS EXAMPLE
# ============================================================
# With our alphabetical successor convention, both BFS
# and DFS select Belgrade next at this point.
#
# We now remove Belgrade-node from the frontier
# and expand it.
#
# After repeated-state checking, the new useful search
# node generated from Belgrade is:
#
#     Zagreb-node
#
#
# Therefore:
# ------------------------------------------------------------
# GENERATED NODES
# ------------------------------------------------------------
# Generated nodes are ONLY the new search nodes created
# during THIS expansion.
#
# Generated now:
#
#     Zagreb-node
# ------------------------------------------------------------
# FRONTIER
# ------------------------------------------------------------
# The frontier contains search nodes that have been
# generated but have NOT yet been expanded.
#
# Belgrade is no longer in the frontier because
# we have just expanded it.
#
# The frontier now contains:
#
#     Budapest-node
#     Sofia-node
#     Zagreb-node
#
# The exact order in which these nodes will be selected
# depends on the search strategy.
# ------------------------------------------------------------
# REACHED
# ------------------------------------------------------------
# Reached contains every STATE discovered so far.
#
# Reached:
#
#     {
#         Bucharest,
#         Belgrade,
#         Budapest,
#         Sofia,
#         Zagreb
#     }
#
# Notice that Belgrade is STILL in reached even though
# it is no longer in the frontier.
# ============================================================
# KEY DISTINCTION
# ============================================================
# Generated:
#     What did this expansion create?
#
# Frontier:
#     What search nodes are still waiting to be explored?
#
# Reached:
#     What states have been discovered at any point so far?
#
#
# After expanding Belgrade:
#
#     Generated = {Zagreb-node}
#
#     Frontier  = {
#         Budapest-node,
#         Sofia-node,
#         Zagreb-node
#     }
#
#     Reached   = {
#         Bucharest,
#         Belgrade,
#         Budapest,
#         Sofia,
#         Zagreb
#     }
#
#
# This makes the difference clearer:
#
#     Belgrade is REACHED,
#     but it is no longer in the FRONTIER.
#
#     Zagreb has just been GENERATED,
#     so it is both in the FRONTIER
#     and represented in REACHED.

# ============================================================
# 13. BREADTH-FIRST SEARCH — BFS
# ============================================================

def bfs(problem, trace=False):
    """
    Breadth-First Search.

    Selection rule:
        shallowest node first

    Frontier:
        FIFO queue

    Repeated states:
        ignored once reached

    Goal test:
        when a child is generated
    """

    root = Node(
        state=problem.initial_state
    )

    if problem.is_goal(root.state):
        return make_result(
            problem,
            root,
            expanded_nodes=0,
            max_frontier=1
        )

    frontier = deque([root])

    reached = {
        root.state
    }

    expanded_nodes = 0
    max_frontier = 1
    step = 0

    while frontier:

        node = frontier.popleft()

        expanded_nodes += 1
        step += 1

        if trace:

            print(
                f"\nSTEP {step}"
            )

            print(
                "POP:",
                pretty_name(node.state)
            )

        for child in expand(
            problem,
            node,
            cost="distance_km"
        ):

            if child.state in reached:
                continue

            reached.add(child.state)

            # BFS can use an early goal test.
            if problem.is_goal(child.state):

                if trace:
                    print(
                        "GOAL GENERATED:",
                        pretty_name(child.state)
                    )

                max_frontier = max(
                    max_frontier,
                    len(frontier) + 1
                )

                return make_result(
                    problem,
                    child,
                    expanded_nodes,
                    max_frontier
                )

            frontier.append(child)

        max_frontier = max(
            max_frontier,
            len(frontier)
        )

        if trace:

            print(
                "Frontier:",
                [
                    pretty_name(n.state)
                    for n in frontier
                ]
            )

            print(
                "Reached:",
                [
                    pretty_name(s)
                    for s in sorted(reached)
                ]
            )

    return None


# ============================================================
# 14. DEPTH-FIRST SEARCH — DFS
# ============================================================

def dfs(problem, trace=False):
    """
    Depth-First Search.

    Selection rule:
        deepest node first

    Frontier:
        LIFO stack

    We use repeated-state checking so that the algorithm
    does not repeatedly explore the same city.

    Successors are VISITED alphabetically.

    Because the stack is LIFO, children must be pushed
    in reverse alphabetical order.
    """

    root = Node(
        state=problem.initial_state
    )

    frontier = [root]

    reached = {
        root.state
    }

    expanded_nodes = 0
    max_frontier = 1
    step = 0

    while frontier:

        node = frontier.pop()

        step += 1

        if trace:

            print(
                f"\nSTEP {step}"
            )

            print(
                "POP:",
                pretty_name(node.state)
            )

        if problem.is_goal(node.state):

            return make_result(
                problem,
                node,
                expanded_nodes,
                max_frontier
            )

        expanded_nodes += 1

        children = []

        for child in expand(
            problem,
            node,
            cost="distance_km"
        ):

            if child.state not in reached:

                reached.add(child.state)

                children.append(child)

        # expand() returns alphabetical order.
        #
        # Example:
        #
        # [Belgrade, Budapest, Sofia]
        #
        # To visit Belgrade first with a LIFO stack,
        # push:
        #
        # Sofia, Budapest, Belgrade

        for child in reversed(children):
            frontier.append(child)

        max_frontier = max(
            max_frontier,
            len(frontier)
        )

        if trace:

            print(
                "Frontier:",
                [
                    pretty_name(n.state)
                    for n in reversed(frontier)
                ]
            )

            print(
                "Reached:",
                [
                    pretty_name(s)
                    for s in sorted(reached)
                ]
            )

    return None


# ============================================================
# 15. UNIFORM-COST SEARCH — UCS
# ============================================================

def ucs(
    problem,
    cost="distance_km",
    trace=False
):
    """
    Uniform-Cost Search.

    Selection rule:
        lowest accumulated path cost g(n)

    Frontier:
        priority queue

    A state can be reached again if the new route
    is cheaper.

    Goal test:
        when the node is popped from the frontier
    """

    if cost not in {
        "distance_km",
        "time_min"
    }:
        raise ValueError(
            "cost must be 'distance_km' or 'time_min'"
        )

    root = Node(
        state=problem.initial_state,
        path_cost=0
    )

    tie_breaker = count()

    frontier = []

    heapq.heappush(
        frontier,
        (
            0,
            next(tie_breaker),
            root
        )
    )

    # reached[state] contains the cheapest
    # path cost discovered so far.
    reached = {
        root.state: 0
    }

    expanded_nodes = 0
    max_frontier = 1
    step = 0

    while frontier:

        current_cost, _, node = heapq.heappop(
            frontier
        )

        # There may be an older, more expensive entry
        # for the same state still inside the heap.
        #
        # If so, ignore it.
        if current_cost != reached.get(node.state):
            continue

        step += 1

        if trace:

            print(
                f"\nSTEP {step}"
            )

            print(
                f"POP: {pretty_name(node.state)} "
                f"g={current_cost}"
            )

        # UCS uses a late goal test.
        #
        # A generated goal is not necessarily optimal.
        # A goal popped with minimum g(n) is optimal.
        if problem.is_goal(node.state):

            return make_result(
                problem,
                node,
                expanded_nodes,
                max_frontier
            )

        expanded_nodes += 1

        for child in expand(
            problem,
            node,
            cost=cost
        ):

            child_cost = child.path_cost

            # Keep the child if:
            #
            # 1. we have never reached this state, or
            # 2. this is a cheaper path to the state.

            if (
                child.state not in reached
                or
                child_cost < reached[child.state]
            ):

                reached[child.state] = child_cost

                heapq.heappush(
                    frontier,
                    (
                        child_cost,
                        next(tie_breaker),
                        child
                    )
                )

        max_frontier = max(
            max_frontier,
            len(frontier)
        )

        if trace:

            active_frontier = []

            for g, _, n in frontier:

                if reached.get(n.state) == g:

                    active_frontier.append(
                        (
                            g,
                            pretty_name(n.state)
                        )
                    )

            active_frontier.sort()

            print(
                "Frontier:",
                active_frontier
            )

            print(
                "Reached:",
                {
                    pretty_name(s): g
                    for s, g
                    in sorted(reached.items())
                }
            )

    return None


# ============================================================
# 16. RUN ALL SEARCH ALGORITHMS
# ============================================================

bfs_result = bfs(problem)

dfs_result = dfs(problem)

ucs_distance_result = ucs(
    problem,
    cost="distance_km"
)

ucs_time_result = ucs(
    problem,
    cost="time_min"
)

# ============================================================
# 17. PRINT RESULTS
# ============================================================

def print_result(name, result):

    print(
        "\n" + "=" * 70
    )

    print(name)

    print(
        "=" * 70
    )

    if result is None:

        print("No solution found.")
        return

    readable_path = [
        pretty_name(city)
        for city in result["path"]
    ]

    print(
        "Path:",
        " → ".join(readable_path)
    )

    print(
        "Actions:",
        result["actions"]
    )

    print(
        "Distance:",
        result["distance_km"],
        "km"
    )

    total_minutes = result["time_min"]

    hours = total_minutes // 60
    minutes = total_minutes % 60

    print(
        "Time:",
        total_minutes,
        f"minutes ({hours} h {minutes} min)"
    )

    print(
        "Expanded nodes:",
        result["expanded_nodes"]
    )

    print(
        "Maximum frontier size:",
        result["max_frontier"]
    )


print_result(
    "BREADTH-FIRST SEARCH",
    bfs_result
)

print_result(
    "DEPTH-FIRST SEARCH",
    dfs_result
)

print_result(
    "UNIFORM-COST SEARCH — DISTANCE",
    ucs_distance_result
)

print_result(
    "UNIFORM-COST SEARCH — TIME",
    ucs_time_result
)


# ============================================================
# 18. COMPARISON TABLE
# ============================================================

comparison = pd.DataFrame(
    {
        "BFS": {
            "Actions":
                bfs_result["actions"],

            "Distance (km)":
                bfs_result["distance_km"],

            "Time (min)":
                bfs_result["time_min"],

            "Expanded nodes":
                bfs_result["expanded_nodes"],

            "Max frontier":
                bfs_result["max_frontier"]
        },

        "DFS": {
            "Actions":
                dfs_result["actions"],

            "Distance (km)":
                dfs_result["distance_km"],

            "Time (min)":
                dfs_result["time_min"],

            "Expanded nodes":
                dfs_result["expanded_nodes"],

            "Max frontier":
                dfs_result["max_frontier"]
        },

        "UCS — distance": {
            "Actions":
                ucs_distance_result["actions"],

            "Distance (km)":
                ucs_distance_result["distance_km"],

            "Time (min)":
                ucs_distance_result["time_min"],

            "Expanded nodes":
                ucs_distance_result["expanded_nodes"],

            "Max frontier":
                ucs_distance_result["max_frontier"]
        },

        "UCS — time": {
            "Actions":
                ucs_time_result["actions"],

            "Distance (km)":
                ucs_time_result["distance_km"],

            "Time (min)":
                ucs_time_result["time_min"],

            "Expanded nodes":
                ucs_time_result["expanded_nodes"],

            "Max frontier":
                ucs_time_result["max_frontier"]
        }
    }
)

comparison

# ============================================================
# 19. VERIFY WHAT EACH ALGORITHM OPTIMISES
# ============================================================

print(
    "\nBFS number of actions:",
    bfs_result["actions"]
)

print(
    "UCS-distance total distance:",
    ucs_distance_result["distance_km"],
    "km"
)

print(
    "UCS-time total time:",
    ucs_time_result["time_min"],
    "minutes"
)


# BFS:
#
# Optimises the number of actions when searching
# level by level.
#
# It does NOT necessarily minimise distance or time
# when different edges have different costs.
#
#
# UCS — distance:
#
# Uses distance_km as g(n).
#
# Therefore, it returns a minimum-distance route.
#
#
# UCS — time:
#
# Uses time_min as g(n).
#
# Therefore, it returns a minimum-time route.
#
#
# The graph is exactly the same.
#
# Only the action-cost function changes.

# ============================================================
# 20. OPTIONAL — COMPLETE SEARCH TRACES
# ============================================================

# Uncomment ONE at a time to inspect the evolution
# of frontier and reached.


# ------------------------------------------------------------
# BFS TRACE
# ------------------------------------------------------------

# bfs(
#     problem,
#     trace=True
# )


# ------------------------------------------------------------
# DFS TRACE
# ------------------------------------------------------------

# dfs(
#     problem,
#     trace=True
# )


# ------------------------------------------------------------
# UCS — DISTANCE TRACE
# ------------------------------------------------------------

# ucs(
#     problem,
#     cost="distance_km",
#     trace=True
# )


# ------------------------------------------------------------
# UCS — TIME TRACE
# ------------------------------------------------------------

# ucs(
#     problem,
#     cost="time_min",
#     trace=True
# )

# ============================================================
# 21. CONCEPTUAL QUESTIONS — SOLUTIONS
# ============================================================

# Q1.
# Why can BFS return a route with fewer actions
# but a higher total distance?
#
# BFS orders search nodes by depth.
#
# It minimises the number of actions, not the accumulated
# distance.
#
# When action costs differ:
#
#     fewer actions != lower cost


# ------------------------------------------------------------

# Q2.
# Why does DFS depend on successor ordering?
#
# DFS commits to one branch and explores it deeply
# before returning to the alternatives.
#
# Therefore, changing which successor is considered
# first can completely change:
#
#     - the exploration order
#     - the first solution found
#     - the number of nodes expanded


# ------------------------------------------------------------

# Q3.
# Why does UCS use a priority queue?
#
# UCS must always select the frontier node with
# minimum accumulated path cost:
#
#     g(n)
#
# A priority queue maintains exactly this ordering.


# ------------------------------------------------------------

# Q4.
# Why can UCS replace a previously reached route?
#
# Reaching a state does not prove that we have reached
# it through the cheapest possible path.
#
# Example:
#
#     first route to X:
#         g(X) = 900
#
#     later route to X:
#         g(X) = 700
#
# UCS keeps:
#
#     reached[X] = 700


# ------------------------------------------------------------

# Q5.
# Why does UCS test the goal when it is popped,
# rather than when it is generated?
#
# Generating a goal only proves that a solution exists.
#
# There may still be a cheaper partial path in the frontier
# that later reaches the goal with a lower total cost.
#
# UCS therefore stops only when the goal itself is the
# lowest-cost node in the frontier.
#
#     goal generated
#         !=
#     optimality guaranteed
#
#     goal popped with minimum g(n)
#         =
#     optimal solution


# ------------------------------------------------------------

# Q6.
# Which strategy uses the most memory?
#
# For THIS concrete run, inspect:
#
#     comparison.loc["Max frontier"]
#
# The answer should be based on the observed run.
#
# In general:
#
# BFS can consume substantial memory because it keeps
# many nodes from the same depth.
#
# DFS usually keeps much less frontier information.
#
# UCS can also consume substantial memory because many
# alternative low-cost paths may remain in the frontier.


# ------------------------------------------------------------

# Q7.
# What happens if every connection has cost 1?
#
# Then:
#
#     g(n) = depth(n)
#
# Therefore:
#
#     lowest g(n)
#
# and:
#
#     shallowest depth
#
# describe the same ordering criterion.
#
# UCS and BFS therefore become equivalent with respect
# to solution cost/depth, apart from possible tie-breaking.


# ------------------------------------------------------------

# Q8.
# What information are BFS, DFS and UCS still missing?
#
# None of them estimates how far a state is from Rome.
#
# BFS:
#     knows depth
#
# DFS:
#     follows depth-first exploration
#
# UCS:
#     knows cost already spent, g(n)
#
# None of them knows:
#
#     estimated cost remaining to the goal
#
# In the next session we introduce:
#
#     h(n)
#
# the heuristic estimate of the remaining cost.
#
# This leads to informed search and A*.

